#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '2':
        pose: hovergames/pose
        parent_frame_id: odom
    '7':
        pose: obstacle_0/pose
        parent_frame_id: odom

optitrack_config:
       multicast_address: 224.0.0.1
